apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster-2
  region: us-east-1

nodeGroups:
  - name: demo-ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub