---
- name: Install node and npm
  hosts: 167.172.145.81
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: 167.172.145.81
  tasks:
    - name: Create linux user
      user:
        name: laura
        comment: Laura Admin
        group: admin


- name: Deploy nodejs app
  hosts: 167.172.145.81
  become: True
  become_user: laura
  tasks:
    - name: Copy nodejs file to server then unpack the tar
      unarchive:
        src: /home/laura/twn-devops/ansible/nodejs-app-1.0.0.tgz
        dest: /home/laura
    - name: Install dependencies in package.json
      npm:
        path: /home/laura/package
    - name: Start the application
      command: 
        chdir: /home/laura/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}