---
- name: Install node and npm
  host: 167.172.145.81
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: 167.172.145.81
  tasks:
    - name: Copy tar and unpack it