---
- name: Install node and npm
  hosts: 167.172.145.81
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: 167.172.145.81
  tasks:
    - name: Create linux user
      user:
        name: laura
        comment: Laura Admin
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}

- name: Deploy nodejs app
  hosts: 167.172.145.81
  become: True
  become_user: laura
  vars:
    - app_file_directory: /home/laura/twn-devops
    - version: 1.0.0
    - destination: /home/laura
  tasks:
    - name: Copy nodejs file to server then unpack the tar
      unarchive:
        src: "{{app_file_directory}}/ansible/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
      register: user_creation_result
    - debug: msg={{user_creation_result}}
    - name: Install dependencies in package.json
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}