---
- name: Install java and net-tools
  hosts: 68.183.135.3
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack Nexus installer
  hosts: 68.183.135.3
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt
      register: download_result
    - debug: msg={{download_result}}
    - name: Untar Nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: True
    - name: Find nexus folder (with module that matches regex)
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    # - debug: msg={{find_result}}
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result}}
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists